apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: argo-bitbucket-cicd-event-source
  namespace: argo-events
spec:
  type: webhook
  webhook:
    example:
      port: "12000"
      endpoint: /trigger
      method: POST
